%% 03_build_master_table_all_sources.m 
clear; clc;

projectRoot = "C:\Users\Admin.VIG\Desktop\MIA_DL_PROJECT";
imagesRoot  = fullfile(projectRoot, "images", "images");
masksRoot   = fullfile(projectRoot, "masks", "masks");

% DEBUG: print what MATLAB sees
disp("imagesRoot = " + imagesRoot);
disp("masksRoot  = " + masksRoot);

disp("Folders inside imagesRoot:");
disp(string({dir(imagesRoot).name})');

disp("Folders inside masksRoot:");
disp(string({dir(masksRoot).name})');

% ---- Define mapping explicitly ----
sources = [
    struct("name","blood_vessels", ...
        "imgDir", fullfile(imagesRoot, "images blood vessels"), ...
        "maskDir", fullfile(masksRoot, "masks blood vessels"), ...
        "imgExt", ".tif", ...
        "maskExt", ".png")

    struct("name","MTC", ...
        "imgDir", fullfile(imagesRoot, "images MTC"), ...
        "maskDir", fullfile(masksRoot, "masks MTC"), ...
        "imgExt", ".tif", ...
        "maskExt", ".png")

    struct("name","MTC2", ...
        "imgDir", fullfile(imagesRoot, "images MTC2"), ...
        "maskDir", fullfile(masksRoot, "masks MTC2"), ...
        "imgExt", ".tif", ...
        "maskExt", ".tif")

    struct("name","TCGA", ...
        "imgDir", fullfile(imagesRoot, "images TCGA"), ...
        "maskDir", fullfile(masksRoot, "masks TCGA"), ...
        "imgExt", ".tif", ...
        "maskExt", ".png")

    struct("name","omental_1", ...
        "imgDir", fullfile(imagesRoot, "images omental part 1"), ...
        "maskDir", fullfile(masksRoot, "masks omental mets part 1"), ...
        "imgExt", ".tif", ...
        "maskExt", ".png")

    struct("name","omental_2", ...
        "imgDir", fullfile(imagesRoot, "images omental part 2"), ...
        "maskDir", fullfile(masksRoot, "masks omental mets part 2"), ...
        "imgExt", ".tif", ...
        "maskExt", ".png")

    struct("name","GTEX", ...
        "imgDir", fullfile(imagesRoot, "images GTEX"), ...
        "maskDir", fullfile(masksRoot, "masks unet GTEX"), ...
        "imgExt", ".jpg", ...
        "maskExt", ".png")

    struct("name","GTEX_1024", ...
        "imgDir", fullfile(imagesRoot, "images GTEX 1024"), ...
        "maskDir", fullfile(masksRoot, "masks unet GTEX 1024"), ...
        "imgExt", ".tif", ...
        "maskExt", ".png")
];

TAll = table();

for s = 1:numel(sources)
    src = sources(s);

    if ~isfolder(src.imgDir) || ~isfolder(src.maskDir)
        fprintf("SKIP %-12s (missing folder)\n", src.name);
        continue;
    end

    P = build_pairs(src.imgDir, src.maskDir, src.imgExt, src.maskExt);
    P = add_source(P, src.name);

    fprintf("%-12s -> paired: %d\n", src.name, height(P));
    TAll = [TAll; P];
end

fprintf("\nTOTAL paired samples: %d\n", height(TAll));
disp(groupcounts(TAll,"Source"));

save(fullfile(projectRoot, "TAll.mat"), "TAll", "sources");
disp("Saved: TAll.mat");